services:
  - type: web
    name: yt-analyzer-pro-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: YOUTUBE_VIDEO_FETCH_LIMIT
        value: 100
      - key: GEMINI_API_KEY_1
        sync: true
      - key: GEMINI_API_KEY_2
        sync: true
      - key: GEMINI_API_KEY_3
        sync: true
      - key: GEMINI_API_KEY_4
        sync: true
      - key: GEMINI_API_KEY_5
        sync: true
      - key: GEMINI_API_KEY_6
        sync: true
      - key: GROQ_API_KEY
        sync: true
      - key: GOOGLE_CLIENT_ID
        sync: true
      - key: GOOGLE_CLIENT_SECRET
        sync: true
      - key: GOOGLE_REDIRECT_URI
        sync: true
